### ISSUE TITLE
Doesn't return user profile_image_url.

### ISSUE THREAD

**Issue by aneeshpanoli** [alexandrtovmach/react-twitter-login#11]
Does this package use an older API version?

According to twitter docs the call should return profile image URL as well.
[twitter docs](https://developer.twitter.com/en/docs/twitter-api/v1/accounts-and-users/user-profile-images-and-banners)

**Comment by alexandrtovmach** [comment]
@aneeshpanoli Thanks for reporting!
It seems like some misunderstanding of package, It's only about authorization, but docs that you provided about separate API methods and require additional request to `https://api.twitter.com/1.1/users/show.json?user_id=USER_ID`

**Comment by alexandrtovmach** [comment]
![image](https://user-images.githubusercontent.com/28801003/95121476-c4309700-0757-11eb-8249-1a4aab4aa582.png)
