### ISSUE TITLE
Why does the request proxy through heroku cors? shouldn't it be going to twitter directly?

### ISSUE THREAD

**Issue by aneeshpanoli** [alexandrtovmach/react-twitter-login#12]
`https://cors-anywhere.herokuapp.com/` < -- proxies via this. Can you please disable it?

**Comment by alexandrtovmach** [comment]
Please check this issue #3, but thanks for reminder, it's good to add to README

**Comment by alexandrtovmach** [comment]
Added note about proxy usage in #17
