### ISSUE TITLE
error instaling component on react 17.0.2

### ISSUE THREAD

**Issue by HolyGamesCode** [alexandrtovmach/react-twitter-login#26]
Hello

I can install the component using react 17.0.2

I get this error

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
...
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
...
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.3.0" from react-twitter-login@1.4.0
npm ERR! node_modules/react-twitter-login
npm ERR!   react-twitter-login@"*" from the root project

**Comment by HolyGamesCode** [comment]
at your package.json i see that you are using 
    "react": "^16.6.0",
    "react-dom": "^16.6.0",

probable need to be updater to react 17.0.2

**Comment by alexandrtovmach** [comment]
fixed: https://www.npmjs.com/package/react-twitter-login/v/1.5.0
