### ISSUE TITLE
There is cors issue with your proxy, please check screenshot

### ISSUE THREAD

**Issue by MZeeDev** [alexandrtovmach/react-twitter-login#28]
Please check the screenshot
<img width="1440" alt="Screenshot 2021-10-14 at 7 52 49 PM" src="https://user-images.githubusercontent.com/37569858/137342882-6ae938d0-0085-458f-8171-9e0fb7b9aa19.png">
.

**Comment by tayyabferozi** [comment]
> @MZeeDev
> 
> 1. First I'd like to remind: "This package NOT FOR PRODUCTION, because it's require to keep CONSUMER_KEY and CONSUMER_SECRET on client side, which are huge security risk. Use this package for MVP or quick prototype only. If you looking for some production solution, please use server-side authorization like passport-twitter." ([first paragraph in README](https://github.com/alexandrtovmach/react-twitter-login#readme))
> 2. "is not worth it anymore" – it's very rude, because you're using open-source tool for free, which was created on pure enthusiasm and shared with you.

Hi, I am using passport in the backend but don't know how to open the twitter login popup on the front-end, I was using react-twitter-auth but its popup doesn't close. Please suggest any library if this one is not for production.
Thanks

**Comment by alexandrtovmach** [comment]
@tayyabferozi if you're using passport server side auth, then this package not suit for you. This is pure frontend solution
