### ISSUE TITLE
https://cors-anywhere.herokuapp.com why you use this server??? And who own this domain

### ISSUE THREAD

**Issue by AbdurRahamanAR** [alexandrtovmach/react-twitter-login#3]

**Comment by alexandrtovmach** [comment]
That's simple proxy server that used to avoid CORS issues. You can get more details below
Demo          :   https://robwu.nl/cors-anywhere.html
Source code   :   https://github.com/Rob--W/cors-anywhere/
Documentation :   https://github.com/Rob--W/cors-anywhere/#documentation

**Comment by AbdurRahamanAR** [comment]
sorry for disturb you . But i fell unsecured with that's . Is not it's create any security or performance issue on my site.

**Comment by AbdurRahamanAR** [comment]
Is it's will be remain on production

**Comment by alexandrtovmach** [comment]
@AbdurRahamanAR If were talking about client site authorization, there is no issue to use this proxy server on production because it's provide us with temp token only. For more secure authorization you should use server side.

**Comment by alexandrtovmach** [comment]
Added note about proxy usage in #17
