### ISSUE TITLE
Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by gujiwuqing** [alexandrtovmach/react-twitter-login#36]
Access to fetch at 'https://cors.bridged.cc/https://api.twitter.com/oauth/request_token' from origin 'https://alexandrtovmach.github.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/44566835/157186450-775882dc-ef0e-472f-91f7-79ccf4420adc.png">

**Comment by shahankur32** [comment]
I am also facing the same issue

**Comment by gujiwuqing** [comment]
> I am also facing the same issue
It's a pity that no one has solved it, so I was forced to use Twitter's api

**Comment by bobbydank** [comment]
I am also having this issue.
